Fix bot breaking when new users join groups/the team
scrapinghub/slackbot pull request #141
Opened 2017-04-17 04:50 UTC by TetraEtc

This is a resurrection of #117, which was designed to fix the problems with #115 and #61 

Test coverage should be possible. I'm  not sure exactly what tests you'd want though. This lives within the `MessageDispatcher` classes `loop` function, but it primarily relies on `SlackClient` for actual functionality, so if anything a test for `parse_channel_data` should be done.

2017-04-19 19:29 UTC, jtatum requested changes
Thank you so much for recreating the PR, I appreciate it! Tests are possible, but I can see that they might be challenging. Let's get this merged and I'll take a crack at them. Can you briefly detail the testing you've performed on this code? Also, were you able to run the existing functional and unit tests?

2017-04-19 19:29 UTC, jtatum commented on slackbot/dispatcher.py
> +                if event.get('type') == 'message':
rather than repeatedly calling .get(), why not store the type first, like event_type = event.get('type')

2017-04-19 22:15 UTC, TetraEtc commented on slackbot/dispatcher.py
> +                if event.get('type') == 'message':
That is something I can do soon for you :) Not sure if it makes it perform any better in terms of CPU/Memory though. (Probably better for CPU, worse for Memory at a rough guess?)

2017-04-19 22:20 UTC, TetraEtc commented
When it comes to testing it, a similar approach is used in the [slackrtm](https://github.com/llimllib/slackrtm/blob/master/slackrtm/client.py#L45) library. This is then used by the [Limbo slack bot](https://github.com/llimllib/limbo).

2017-04-19 22:56 UTC, jtatum commented on slackbot/dispatcher.py
> +                if event.get('type') == 'message':
More about style than performance. Even on a very busy slack, neither memory nor cpu is going to be a factor with this code.

2017-04-19 23:05 UTC, TetraEtc commented on slackbot/dispatcher.py
> +                if event.get('type') == 'message':
That's fine. Once I've got a little bit of spare time I'll make that change for you :)

2017-04-21 19:23 UTC, jtatum approved these changes

2017-04-21 19:24 UTC, merged

2017-04-24 23:20 UTC, tehranian commented
Thanks guys for fixing this! When are you planning to ship a release to PyPI?

2017-04-24 23:48 UTC, jtatum commented
@tehranian, I haven't heard from @lins05 in a while, but I think I can cut a release. I still want to add some tests for this code, and I need to make a changelog. Maybe next weekend? In the meantime, feel free to use setup.py install to install the version from the develop branch on github.