Add a token header when downloading file
scrapinghub/slackbot pull request #149
Opened 2017-05-22 11:33 UTC by kriw

It supports downloading file uploaded on slack.
Related issue: https://github.com/lins05/slackbot/issues/99

2017-05-28 08:07 UTC, lins05 requested changes

2017-05-28 08:07 UTC, lins05 commented on slackbot/utils.py
> +    r = requests.get(url, stream=True, headers={"Authorization": "Bearer "+token})
Please only include the `headers` kwarg when token is not empty.

2017-05-29 02:53 UTC, merged

2017-06-14 22:34 UTC, jtatum commented
@kriw can you explain how to use this to download files? Where should the token value come from?

2017-06-15 01:53 UTC, kriw commented
The token is your Slack API Token.  
This is the example.
```py
@respond_to("uploaded a file: \<?(.*)\>? .* commented: checksec")
def mention_download(message, url):
    if not 'file' in message.body:
        return

    url = message.body['file']['url_private']
    message.send("OK")
    if url.startswith('http'):
        with create_tmp_file() as tmpf:
            import secret
            download_file(url, tmpf, secret.API_TOKEN)
            message.channel.upload_file(url, tmpf,
                    'downloaded from {}'.format(url))
```
and

This is `secret.py` included in above file.
```py
API_TOKEN = "xxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx"
```