Slackclient passes through slacker rtm start params
scrapinghub/slackbot pull request #208
Opened 2020-02-13 20:46 UTC by louhow

Details on these params can be found here: https://api.slack.com/methods/rtm.start

In particular, `simple_latest` and `no_unreads` both are helpful for improving performance on startup

2020-02-16 07:08 UTC, lucywang000 requested changes

2020-02-16 07:08 UTC, lucywang000 commented on slackbot/slackclient.py
> +                 rtm_simple_latest=False, rtm_no_unreads=False, rtm_mpim_aware=False):
It's better to put all these rtm args in a single parameter "rtm_args", which shall be of type dict and default to be `None`. Otherwise the argument list could grow again if more args are added in the future

2020-02-18 02:56 UTC, louhow commented on slackbot/slackclient.py
> +                 rtm_simple_latest=False, rtm_no_unreads=False, rtm_mpim_aware=False):
👍 agreed!

2020-02-18 09:29 UTC, merged

2020-02-18 09:29 UTC, lucywang000 commented
Thx for the patch!

2020-06-11 18:28 UTC, louhow commented
@lucywang000 would you be willing to do a release with this?

2020-06-12 01:51 UTC, lucywang000 commented
@louhow Released 1.0.0 version (remove python 2 support too).